# Generated by Django 4.0 on 2021-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(default='null', max_length=500)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(default='null', max_length=100)),
                ('country', models.CharField(default='null', max_length=100)),
                ('address', models.CharField(default='null', max_length=1000)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='null', max_length=100)),
                ('aboutyou', models.TextField(default='null', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='degree_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.TextField(max_length=1000)),
                ('degreecity', models.TextField(max_length=1000)),
                ('university', models.TextField(max_length=1000)),
                ('degreepercent', models.TextField(max_length=100)),
                ('degreestartmonth', models.CharField(max_length=1000)),
                ('degreestartyear', models.IntegerField()),
                ('degreeendmonth', models.CharField(max_length=1000)),
                ('degreeendyear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='extra_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies1', models.CharField(max_length=1000)),
                ('hobbies2', models.CharField(max_length=1000)),
                ('achivements1', models.CharField(max_length=1000)),
                ('achivements2', models.CharField(max_length=1000)),
                ('extra', models.CharField(max_length=1000)),
                ('strengths1', models.CharField(max_length=1000)),
                ('strengths2', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='intermediate_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediate', models.TextField(max_length=1000)),
                ('intercity', models.TextField(max_length=1000)),
                ('college', models.TextField(max_length=1000)),
                ('interstartmonth', models.CharField(max_length=1000)),
                ('interstartyear', models.IntegerField()),
                ('interendmonth', models.CharField(max_length=1000)),
                ('interendyear', models.IntegerField()),
                ('interpercent', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.TextField(max_length=1000)),
                ('jobcity', models.TextField(max_length=1000)),
                ('companyname', models.TextField(max_length=1000)),
                ('jobstartmonth', models.CharField(max_length=1000)),
                ('jobstartyear', models.IntegerField()),
                ('jobendmonth', models.CharField(max_length=1000)),
                ('jobendyear', models.IntegerField()),
                ('project', models.TextField(max_length=1000)),
                ('internship', models.TextField(max_length=1000)),
                ('projectteam', models.TextField(max_length=1000)),
                ('position', models.TextField(max_length=1000)),
                ('projecttitle', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='school_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolboard', models.TextField(max_length=1000)),
                ('schoolcity', models.TextField(max_length=1000)),
                ('school', models.TextField(max_length=1000)),
                ('schoolstartmonth', models.CharField(max_length=1000)),
                ('schoolstartyear', models.IntegerField()),
                ('schoolendmonth', models.CharField(max_length=1000)),
                ('schoolendyear', models.IntegerField()),
                ('schoolpercent', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programSkill', models.TextField(max_length=1000)),
                ('operatingSkill', models.TextField(max_length=1000)),
                ('DatabaseSkill', models.TextField(max_length=1000)),
                ('IDESkill', models.TextField(max_length=1000)),
                ('FrameworkSkill', models.TextField(max_length=1000)),
                ('otherSkill', models.TextField(max_length=1000)),
            ],
        ),
    ]
